language: scala
scala:
- 2.12.2
- 2.11.8
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
notifications:
  slack:
    secure: GBYBKXU+zIYdRDRZPoWREW0PubZWmZZSiQxWehP6rg/m02vv7bq1MNaTk4fZHc59VkisnVWLbtSW2kqdJup58Uw19OdgoqC50A/eeARL+dRH6LXmcmTco423T2kxj8n0FsIa0JnOSiqNCDlo0hXhabTx8hzmxK5V2STWM+jUqJ+193vEXIqKG+VNGmvXt6L71NGWWLuoFhcfVWzWuHynPWHGkBBh+TKaPELmTJRp9wYUkklJY+SUGV/Xv5NjzP3BMO5z4948J9hXhsuVmwSYkMPju8jmX5rCZvIUjoJiO4dvO7k9XiyH2HDzJa+pI8Lj7Td6OnahOEnFwMBTfh9+F+neGnhVaj0eMO6evx17CuyOo6PaLs5bO3m/hMKIOgM/VEKeMZ+g8dnmB/V5qrvmYXzFxit00ZnTYGHD8WauK/8SAUGSi0XxcO3qAtl2EeL8sJZN6BpUOsN/kmfv7z4/EU4s9u/6TDs6KPpeburlq87jAglSudVjQUOWmIwmbQPjD9e0zBXA9tUUbu9fYxKatCVSsYvzHAg3rWAmH/TxvZ+TcqxyDuBi/kYQm1dp2f47Irl8m69DgOUIIRSxz81rOwwBfjJ5Wmrg5qbfPVVdsn6i6mxa41EFSsvaHvSVQ4N0uZQObT6Af4s+sGrt6ZjA6esXdDPB5Keoli9MMcRwLO8=
